<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class PegawaiSeeder extends Seeder
{
    public function run()
    {
        $data = [
            // [
            // 'nip' => 'admin',
            // 'nama' => 'Admin',
            // 'jenis_kelamin' => '-',
            // 'alamat' => '-',
            // 'no_handphone' => '000000000000',
            // 'divisi' => 'Admin',
            // 'jabatan' => 'Admin',
            // 'foto' => 'admin.jpg',
            // 'tanggal_lahir' => '0000-00-00',
            // 'tanggal_masuk' => '0000-00-00',
            // 'clock_in_out_location' => '',
            // ],
            // [
            // 'nip' => '123456',
            // 'nama' => 'Budi',
            // 'jenis_kelamin' => 'Laki-laki',
            // 'alamat' => 'Jl. Contoh No. 1',
            // 'no_handphone' => '08123456789',
            // 'divisi' => 'IT',
            // 'jabatan' => 'Developer',
            // 'foto' => '',
            // 'tanggal_lahir' => '1990-01-01',
            // 'tanggal_masuk' => '2020-01-01',
            // 'clock_in_out_location' => '1',
            // ],
            [
                'nip' => '22020083',
                'nama' => 'GANDA SULISTIYO',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Dsn. Menyanggon, RT. 026 / RW. 011, Ds. Kletek, Kec. Taman, Kab. Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'OPERASIONAL DAN PRODUKSI',
                'jabatan' => 'Head Of Production',
                'foto' => '',
                'tanggal_lahir' => '1987-12-25',
                'tanggal_masuk' => '2022-02-14',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '22110090',
                'nama' => 'ANDROMEDA FORY NIRWANA',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Jl. Karangrejo, RT. 002 / RW. 005, Ds. Gabusbanaran, Kec. Tembelang, Kab. Jombang',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'OPERASIONAL DAN PRODUKSI',
                'jabatan' => 'Production SPV',
                'foto' => '',
                'tanggal_lahir' => '1996-12-06',
                'tanggal_masuk' => '2022-11-01',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '93080018',
                'nama' => 'MUSLIMIN',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Perum Graha Properindo Blok CC-2, RT. 037 / RW. 013, Ds. Kebonagung, Kec. Sukodono, Kab. Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'OPERASIONAL DAN PRODUKSI',
                'jabatan' => 'Pengawas Staff Gudang Peralatan',
                'foto' => '',
                'tanggal_lahir' => '1973-06-05',
                'tanggal_masuk' => '1993-08-24',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '94040028',
                'nama' => 'WEDO PRASETYO',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Griya Bhayangkara D-4, RT. 024 / RW. 005, Ds. Suko, Kec. Sukodono, Kab. Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'OPERASIONAL DAN PRODUKSI',
                'jabatan' => 'Kabag. Logistik dan Umum',
                'foto' => '',
                'tanggal_lahir' => '1959-04-16',
                'tanggal_masuk' => '1994-04-01',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '19060075',
                'nama' => 'FENNY SURYANI',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Jl. Sidosermo PDK I-A No. 367, RT. 001 / RW. 008, Kel. Sidosermo, Kec. Sidosermo, Kota Surabaya',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'OPERASIONAL DAN PRODUKSI',
                'jabatan' => 'Purchasing',
                'foto' => '',
                'tanggal_lahir' => '1981-02-22',
                'tanggal_masuk' => '2019-06-12',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '24110108',
                'nama' => 'RIZKY ACHMAD SETYAWAN',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'G. Bhayangkara Permai L1-20, RT. 020 / RW. 008, Kel. Urangagung, Kec. Sidoarjo, Kabupaten Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'OPERASIONAL DAN PRODUKSI',
                'jabatan' => 'Admin Garasi & Transportasi',
                'foto' => '',
                'tanggal_lahir' => '2000-10-10',
                'tanggal_masuk' => '2024-11-29',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '95030036',
                'nama' => 'TITIK MULYANI',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Bangsri, RT. 003 / RW. 001, Ds. Bangsri, Kec. Sukodono, Kab. Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'OPERASIONAL DAN PRODUKSI',
                'jabatan' => 'Pengawas Bag. Drawing & Kawat Pelurus',
                'foto' => '',
                'tanggal_lahir' => '1972-04-18',
                'tanggal_masuk' => '1995-03-21',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '24100107',
                'nama' => 'RADITYA BAGUS PRASETYO',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Raya Kalijaten No. 59, RT. 001 / RW. 001, Kelurahan Kalijaten Kecamatan Taman, Kabupaten Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'OPERASIONAL DAN PRODUKSI',
                'jabatan' => 'Kepala Pengawas Umum',
                'foto' => '',
                'tanggal_lahir' => '1985-09-04',
                'tanggal_masuk' => '2024-10-07',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '91120004',
                'nama' => 'FAUZUL ADHIM',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Perumahan Sukodono Indah Blok A No. 15 A, RT. 001 / RW. 001, Ds. Sukodono, Kec. Sukodono, Kab. Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'OPERASIONAL DAN PRODUKSI',
                'jabatan' => 'Pengawas Umum',
                'foto' => '',
                'tanggal_lahir' => '1968-03-15',
                'tanggal_masuk' => '1991-12-05',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '14080072',
                'nama' => 'ADITYA WAHYU RAHMANTO',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Anggaswangi, RT. 007 / RW. 004, Ds. Anggaswangi, Kec. Sukodono, Kab. Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'OPERASIONAL DAN PRODUKSI',
                'jabatan' => 'Pengawas Umum',
                'foto' => '',
                'tanggal_lahir' => '1994-01-13',
                'tanggal_masuk' => '2014-08-04',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '98040043',
                'nama' => 'MOH. SHOLEH',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Sukodono, RT. 020 / 005, Ds. Sukodono, Kec. Sukodono, Kab. Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'OPERASIONAL DAN PRODUKSI',
                'jabatan' => 'Office Boy & Kebersihan',
                'foto' => '',
                'tanggal_lahir' => '1977-08-22',
                'tanggal_masuk' => '1998-04-22',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '03040062',
                'nama' => 'M. FITRUR ROSUL',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Pademonegoro, RT. 008 / RW. 002, Ds. Pademonegoro, Kec. Sukodono, Kab. Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'OPERASIONAL DAN PRODUKSI',
                'jabatan' => 'Office Boy & Kebersihan',
                'foto' => '',
                'tanggal_lahir' => '1983-02-12',
                'tanggal_masuk' => '2003-04-10',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '20070078',
                'nama' => 'TRACY AMELIA',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Jl. Simokerto 54, RT. 005 / RW. 004, Kel. Simokerto, Kec. Simokerto, Kota Surabaya',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'SALES & MARKETING',
                'jabatan' => 'SPV Marketing',
                'foto' => '',
                'tanggal_lahir' => '1996-08-27',
                'tanggal_masuk' => '2020-07-01',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '20080079',
                'nama' => 'CHARLES WILSON',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Jl. Tangkuban Perahu No. 45, RT. 001 / RW. 004, Kel. Kota Tinggi, Kec. Pekanbaru Kota, Kota Pekanbaru',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'SALES & MARKETING',
                'jabatan' => 'Staf Marketing',
                'foto' => '',
                'tanggal_lahir' => '1997-03-10',
                'tanggal_masuk' => '2020-08-24',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '23060097',
                'nama' => 'CAMELA PUTERI',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'KP. Tlogosari Selatan, RT. 003 / RW. 001, Ds. Tlogosari, Kec. Sumbermalang, Kab. Situbondo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'SALES & MARKETING',
                'jabatan' => 'Staf Marketing (ASO)',
                'foto' => '',
                'tanggal_lahir' => '1995-06-26',
                'tanggal_masuk' => '2023-06-05',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '24020104',
                'nama' => 'DEVI OKTAVIA',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Jl. Simogirang RT. 002 / RW. 005, Kel. Simogirang, Kec. Prambon, Kabupaten Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'SALES & MARKETING',
                'jabatan' => 'Staf Administrasi',
                'foto' => '',
                'tanggal_lahir' => '1998-10-21',
                'tanggal_masuk' => '2024-02-26',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '20100080',
                'nama' => 'PRISCILLIA CHIUNO JAPFRY',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Amir Machmud IX Blok - A/1, RT. 001 / RW. 008, Kel. Gunung Anyar, Kec. Gunung Anyar, Kota Surabaya',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'SALES & MARKETING',
                'jabatan' => 'SPV Branding',
                'foto' => '',
                'tanggal_lahir' => '1993-04-24',
                'tanggal_masuk' => '2020-10-01',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '22060085',
                'nama' => 'KARIN SUGIONO SINDARTO',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Jl. Raya Kalijaten 88, RT. 001 / RW. 001, Ds. Kalijaten, Kec. Taman, Kab. Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'SALES & MARKETING',
                'jabatan' => 'Admin Logistik',
                'foto' => '',
                'tanggal_lahir' => '1999-02-02',
                'tanggal_masuk' => '2022-06-06',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '23120101',
                'nama' => 'ARDELIA RISKY DWI KURNIAPUTRI',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Donowati 2-A/21, RT. 003 / RW. 001, Kel. Sukomanunggal, Kec. Sukomanunggal, Kota Surabaya',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'SALES & MARKETING',
                'jabatan' => 'Coord. Admin sales',
                'foto' => '',
                'tanggal_lahir' => '1996-05-30',
                'tanggal_masuk' => '2023-12-18',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '22090089',
                'nama' => 'ROSALIA DWI NURFARIDA',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Dsn. Sampuri, RT. 001 / RW. 003, Ds. Karangpuri, Kec. Wonoayu, Kab. Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'SALES & MARKETING',
                'jabatan' => 'Admin sales',
                'foto' => '',
                'tanggal_lahir' => '1994-04-24',
                'tanggal_masuk' => '2022-09-05',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '22030084',
                'nama' => 'M. NUR CHOLIS',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Gubeng Masjid 2/45-B, RT. 011 / RW. 007, Ds. Pacar Keling, Kec. Tambak Sari, Kota. Surabaya',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'SALES & MARKETING',
                'jabatan' => 'Visual Communication',
                'foto' => '',
                'tanggal_lahir' => '1996-05-01',
                'tanggal_masuk' => '2022-03-01',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '23010091',
                'nama' => 'RIZKY WIBISONO',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Perum Jasa Marga Green Residence Blok AD No. 18, RT. 006 / RW. 005, Kel. Kendal Pecabean, Kec. Candi, Kabupaten Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'SALES & MARKETING',
                'jabatan' => 'Wakabag. Inventori Barang Jadi',
                'foto' => '',
                'tanggal_lahir' => '1995-05-13',
                'tanggal_masuk' => '2023-01-09',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '23120100',
                'nama' => 'TEDY WIBOWO',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Jl. Perumahan Pondok Benowo Indah Blok A – 1 No. 5, RT. 001 / RW. 011, Kel. Babat Jerawat, Kec. Pakal, Kota Surabaya',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'SALES & MARKETING',
                'jabatan' => 'Kepala Gudang Inventori (Paku)',
                'foto' => '',
                'tanggal_lahir' => '1990-02-16',
                'tanggal_masuk' => '2023-12-12',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '22060086',
                'nama' => 'SUGIARTO',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Duran, RT. 004 / RW. 002, Ds. Karangpuri, Kec. Wonoayu, Kab. Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'SALES & MARKETING',
                'jabatan' => 'Kep. Gudang Ria I',
                'foto' => '',
                'tanggal_lahir' => '1979-01-01',
                'tanggal_masuk' => '2022-06-13',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '97040041',
                'nama' => 'ALIMIN',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Genengan, RT. 006 / RW. 002, Ds. Popoh, Kec. Wonoayu, Kab. Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'SALES & MARKETING',
                'jabatan' => 'Kep. Gudang Ria II',
                'foto' => '',
                'tanggal_lahir' => '1974-02-03',
                'tanggal_masuk' => '1997-04-01',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '13120071',
                'nama' => 'IRWAN SUSANTO',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Jl. Nyi Cempo Barat, RT. 014 / RW. 005, Ds. Kedungturi, Kec. Taman, Kab. Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'SALES & MARKETING',
                'jabatan' => 'Kep. Gudang Ria III',
                'foto' => '',
                'tanggal_lahir' => '1980-08-14',
                'tanggal_masuk' => '2013-12-16',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '93110022',
                'nama' => 'SLAMET SURYONO',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Dsn. Kletek, RT. 014 / RW. 006, Ds. Kletek, Kec. Taman, Kab. Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'SALES & MARKETING',
                'jabatan' => 'Kepala Bagian Timbangan',
                'foto' => '',
                'tanggal_lahir' => '1973-11-10',
                'tanggal_masuk' => '1993-11-02',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '24070106',
                'nama' => 'ACHMAD YULIANTO',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Dsn. Jeruk RT. 002 / RW. 002, Kel. Jeruk Gamping, Kec. Krian, Kabupaten Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'SALES & MARKETING',
                'jabatan' => 'Kep. Gudang Ria IV',
                'foto' => '',
                'tanggal_lahir' => '1992-07-12',
                'tanggal_masuk' => '2024-07-24',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '13100070',
                'nama' => 'OKKY SETYAWAN',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Griya Bhayangkara D-4, RT. 024 / RW. 005, Ds. Suko, Kec. Sukodono, Kab. Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'SALES & MARKETING',
                'jabatan' => 'Staf Administrasi Penjualan',
                'foto' => '',
                'tanggal_lahir' => '1987-11-07',
                'tanggal_masuk' => '2013-10-07',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '92090008',
                'nama' => 'SUMILAH',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Dsn. Kanigoro, RT. 009 / RW. 003, Ds. Keboharan, Kec. Krian, Kab. Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'SALES & MARKETING',
                'jabatan' => 'Staf Administrasi Penjualan',
                'foto' => '',
                'tanggal_lahir' => '1972-04-10',
                'tanggal_masuk' => '1992-09-10',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '23080099',
                'nama' => 'JORDAN SINDARTO',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Jl. Ngagel Jaya Tengah VIII No. 4, RT. 002 / RW. 002, Kel. Pucang Sewu, Kec. Gubeng, Kota Surabaya',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'FINANCE & ACCOUNTING',
                'jabatan' => 'SPV Finance & Accounting',
                'foto' => '',
                'tanggal_lahir' => '2001-06-06',
                'tanggal_masuk' => '2023-08-01',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '92100009',
                'nama' => 'SRI WAHYUNI',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Kletek, RT. 017 / RW. 007, Ds. Kletek, Kec. Taman, Kab. Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'FINANCE & ACCOUNTING',
                'jabatan' => 'Staf Accounting',
                'foto' => '',
                'tanggal_lahir' => '1970-07-01',
                'tanggal_masuk' => '1992-10-19',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '96070040',
                'nama' => 'FERIDA KESUMA',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Jl. Kesatrian Terusan C-8, RT. 003 / RW. 008, Kel. Kesatrian, Kec. Blimbing, Kota. Malang',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'FINANCE & ACCOUNTING',
                'jabatan' => 'Staf Accounting',
                'foto' => '',
                'tanggal_lahir' => '1973-02-06',
                'tanggal_masuk' => '1996-07-01',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '93010012',
                'nama' => 'ERLIN RETNOWATI',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Suratan VII / 22, RT. 002 / RW. 001, Kel. Kranggan, Kec. Kranggan, Kota Mojokerto',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'FINANCE & ACCOUNTING',
                'jabatan' => 'Staf Administrasi Penjualan',
                'foto' => '',
                'tanggal_lahir' => '1966-12-08',
                'tanggal_masuk' => '1993-01-19',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '93010010',
                'nama' => 'NUNIK SETYOWATI',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Jabaran, RT. 008 / RW. 003, Ds. Jabaran, Kec. Balongbendo, Kab. Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'FINANCE & ACCOUNTING',
                'jabatan' => 'Staf Gudang',
                'foto' => '',
                'tanggal_lahir' => '1972-08-30',
                'tanggal_masuk' => '1993-01-08',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '94020026',
                'nama' => 'CHURUL FAIZAH',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Tanjungsari, RT. 008 / RW. 001, Ds. Tanjungsari, Kec. Taman, Kab. Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'FINANCE & ACCOUNTING',
                'jabatan' => 'Staf Gudang',
                'foto' => '',
                'tanggal_lahir' => '1974-02-18',
                'tanggal_masuk' => '1994-02-01',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '24010102',
                'nama' => 'VENI GERHANA PUTRI',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Kapas Madya 3-I/36, RT.013 / RW. 001, Kel. Kapasmadya Baru, Kec. Tambaksari, Kota Surabaya',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'FINANCE & ACCOUNTING',
                'jabatan' => 'Tax Manager',
                'foto' => '',
                'tanggal_lahir' => '1997-09-17',
                'tanggal_masuk' => '2024-01-03',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '03040063',
                'nama' => 'Y. RONNY SUBIAKTO',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Jl. Tampomas Selatan III No. 10, RT. 006 / RW. 001, Kel. Petompon, Kec. Gajah Mungkur, Kota Semarang',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'FINANCE & ACCOUNTING',
                'jabatan' => 'Staff Pajak',
                'foto' => '',
                'tanggal_lahir' => '1971-04-12',
                'tanggal_masuk' => '2003-04-10',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '93110023',
                'nama' => 'TRESIA ANNA WATI',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Perum Graha Properindo Blok CC-2, RT. 037 / RW. 013, Ds. Kebonagung, Kec. Sukodono, Kab. Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'FINANCE & ACCOUNTING',
                'jabatan' => 'Staff Pajak',
                'foto' => '',
                'tanggal_lahir' => '1972-01-03',
                'tanggal_masuk' => '1993-11-11',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '93080016',
                'nama' => 'ANIS MAHFUDYASARI',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Plaosan, RT. 004 / RW. 002, Ds. Plaosan, Kec. Wonoayu, Kab. Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'FINANCE & ACCOUNTING',
                'jabatan' => 'Staff Pajak',
                'foto' => '',
                'tanggal_lahir' => '1974-01-10',
                'tanggal_masuk' => '1993-08-03',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '98080044',
                'nama' => 'UTAMI',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Wonocolo, RT.009 / RW. 002, Ds. Wonocolo, Kec. Taman, Kab. Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'FINANCE & ACCOUNTING',
                'jabatan' => 'Staff Pajak',
                'foto' => '',
                'tanggal_lahir' => '1968-07-27',
                'tanggal_masuk' => '1998-08-01',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '22080087',
                'nama' => 'MONICA DEWI MAHARANI',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Medayu Utara XIII/62, Kel. Medokan Ayu, Kec. Rungkut, Kota Surabaya',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'FINANCE & ACCOUNTING',
                'jabatan' => 'Staff Pajak',
                'foto' => '',
                'tanggal_lahir' => '1995-04-29',
                'tanggal_masuk' => '2022-08-08',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '99070054',
                'nama' => 'MOH. SHOKIB',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Cangkirsari, RT. 016 / RW. 005, Ds. Cangkirsari, Kec. Sukodono, Kab. Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'HRD & SECURITY',
                'jabatan' => 'HR - Industrial Relationship',
                'foto' => '',
                'tanggal_lahir' => '1973-05-08',
                'tanggal_masuk' => '1999-07-08',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '24010103',
                'nama' => 'MUHAMMAD RIDUWAN YASIN',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Bogem, RT. 003 / RW. 001, Ds. Bogempinggir, Kec. Balongbendo, Kab. Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'HRD & SECURITY',
                'jabatan' => 'SPV Legal - HSE',
                'foto' => '',
                'tanggal_lahir' => '1998-09-27',
                'tanggal_masuk' => '2024-01-03',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '25010109',
                'nama' => 'MUHAMMAD RASYID RADIANTO',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Jl. Ngrojo, RT. 002 / RW. 001, Kel. Bronjong, Kec. Bluluk, Kabupaten Lamongan',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'HRD & SECURITY',
                'jabatan' => 'Staf HSE',
                'foto' => '',
                'tanggal_lahir' => '1990-12-22',
                'tanggal_masuk' => '2025-01-03',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '11100066',
                'nama' => 'FIRMAN AGUNG. K',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Durung Bedug, RT. 004 / RW. 001, Ds. Durung Bedug, Kec. Candi, Kab. Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'HRD & SECURITY',
                'jabatan' => 'Security',
                'foto' => '',
                'tanggal_lahir' => '1993-07-29',
                'tanggal_masuk' => '2011-10-05',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '98080045',
                'nama' => 'EDY SAPUTRA',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Pejaya Anugrah Blok YY/18, Ds. Kramatjegu, Kec. Taman, Kab. Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'HRD & SECURITY',
                'jabatan' => 'Security',
                'foto' => '',
                'tanggal_lahir' => '1963-10-16',
                'tanggal_masuk' => '1998-08-01',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '08040065',
                'nama' => 'SUPARMAN',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Dsn. Klutuk, RT. 001 / RW. 002, Ds. Kramatjegu, Kec. Taman, Kab. Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'HRD & SECURITY',
                'jabatan' => 'Security',
                'foto' => '',
                'tanggal_lahir' => '1975-05-06',
                'tanggal_masuk' => '2008-04-08',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '98080046',
                'nama' => 'HARTOYO',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Kramatjegu W-9, RT. 001 / RW. 002, Ds. Kramatjegu, Kec. Taman, Kab. Sidoarjo',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'HRD & SECURITY',
                'jabatan' => 'Security',
                'foto' => '',
                'tanggal_lahir' => '1968-05-12',
                'tanggal_masuk' => '1998-08-01',
                'clock_in_out_location' => '1',
            ],
            [
                'nip' => '99020051',
                'nama' => 'SUWONO WAGIRAN',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Kebonsari 2/1, RT. 004 / RW. 001, Kel. Kebonsari, Kec. Jambangan, Kota Surabaya',
                'no_handphone' => '0000-0000-0000',
                'divisi' => 'HRD & SECURITY',
                'jabatan' => 'Security',
                'foto' => '',
                'tanggal_lahir' => '1964-07-17',
                'tanggal_masuk' => '1999-02-15',
                'clock_in_out_location' => '1',
            ]
        ];

        $this->db->table('pegawai')->insertBatch($data);

        echo "Seeder berhasil! Total " . count($data) . " data pegawai telah diimport.\n";
    }
}