<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class UserSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
            'id_pegawai' => 1,
            'username' => 'admin',
            'password' => password_hash('admin', PASSWORD_DEFAULT),
            'status' => '',
            'role' => 'Admin',
            ],
            [
            'id_pegawai' => 2,
            'username' => 'budi',
            'password' => password_hash('budi', PASSWORD_DEFAULT),
            'status' => 'Tetap',
            'role' => 'Pegawai',
            ],
            [
            'id_pegawai' => 3,
            'username' => 'ari',
            'password' => password_hash('ari', PASSWORD_DEFAULT),
            'status' => 'Tetap',
            'role' => 'Kepala Bagian',
            ],
            [
            'id_pegawai' => 4,
            'username' => 'yon',
            'password' => password_hash('yon', PASSWORD_DEFAULT),
            'status' => 'Tetap',
            'role' => 'Direktur',
            ],
            // [
            //     'id_pegawai' => 7,
            //     'username' => 'ganda',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 8,
            //     'username' => 'andro',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 9,
            //     'username' => 'muslimin',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 10,
            //     'username' => 'wedo',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 11,
            //     'username' => 'fenny',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 12,
            //     'username' => 'rizky achmad',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Kontrak',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 13,
            //     'username' => 'yani',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 14,
            //     'username' => 'radit',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Kontrak',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 15,
            //     'username' => 'fauzul',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 16,
            //     'username' => 'aditya',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 17,
            //     'username' => 'sholeh',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 18,
            //     'username' => 'rosul',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 19,
            //     'username' => 'tracy',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 20,
            //     'username' => 'charles',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 21,
            //     'username' => 'camela',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Kontrak',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 22,
            //     'username' => 'devi',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Kontrak',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 23,
            //     'username' => 'priscil',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 24,
            //     'username' => 'karin',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 25,
            //     'username' => 'ardel',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Kontrak',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 26,
            //     'username' => 'rosa',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 27,
            //     'username' => 'cholis',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 28,
            //     'username' => 'rizky wibisono',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 29,
            //     'username' => 'tedy',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Kontrak',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 30,
            //     'username' => 'sugiarto',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 31,
            //     'username' => 'alimin',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 32,
            //     'username' => 'irwan',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 33,
            //     'username' => 'slamet',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 34,
            //     'username' => 'yulianto',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Kontrak',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 35,
            //     'username' => 'okky',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 36,
            //     'username' => 'sumilah',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 37,
            //     'username' => 'jordan',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 38,
            //     'username' => 'yuni',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 39,
            //     'username' => 'ferida',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 40,
            //     'username' => 'erlin',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 41,
            //     'username' => 'nunik',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 42,
            //     'username' => 'churul',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 43,
            //     'username' => 'veni',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Kontrak',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 44,
            //     'username' => 'ronny',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 45,
            //     'username' => 'anna',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 46,
            //     'username' => 'anis',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 47,
            //     'username' => 'utami',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 48,
            //     'username' => 'monica',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 49,
            //     'username' => 'shokib',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 50,
            //     'username' => 'riduwan',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Kontrak',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 51,
            //     'username' => 'rasyid',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Kontrak',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 52,
            //     'username' => 'agung',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 53,
            //     'username' => 'edy',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 54,
            //     'username' => 'parman',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 55,
            //     'username' => 'hartoyo',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ],
            // [
            //     'id_pegawai' => 56,
            //     'username' => 'suwono',
            //     'password' => password_hash('123456', PASSWORD_DEFAULT),
            //     'status' => 'Tetap',
            //     'role' => 'Pegawai',
            // ]
        ];

        $this->db->table('users')->insertBatch($data);

        echo "UserSeeder berhasil! Total " . count($data) . " data user telah diimport.\n";
    }
}